name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install browsers
        run: |
          playwright install --with-deps

      - name: Run tests
        # continue-on-error: true
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        run: |
          pytest --alluredir=allure-results || true

      - name: Create Environment Info
        if: always()
        run: |
          echo "Environment=QA" > allure-results/environment.properties
          echo "Framework=Admin Automation" >> allure-results/environment.properties
          echo "Browser=Chromium" >> allure-results/environment.properties
          echo "Execution=GitHub Actions" >> allure-results/environment.properties

      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Pages Artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4